#!/usr/bin/bash


# This file holds all the variables that will be loaded and used to setup
# your Debian installation.  Please customize this for EACH computer and save
# it in something like the ~/Setup directory (can be configured to use a
# different directory in the *-setup.sh script itself.  Doing so will prevent
# merge errors in case you do a git pull later for a newer version.


# To disable a setting below, simply comment out the entire line
rm_dotfiles=1 # Remove all old .dotfiles (from prior Linux distributions)
GRUB_CMDLINE_LINUX_DEFAULT='quiet splash'
#     Above setting is for /etc/default/grub, boot-time hardware parameters go there, separated by spaces
#     "pci=noaer" to avoid errors on Toshiba
#     "i915.enable_psr=0" for smoother mouse movement on Framework
#     "module_blacklist=hid_sensor_hub" for brightness buttons on Framework
extra_repos=1 # Add contrib and non-free to sources.list
ssd=1 # Comment if installed to a spinning HDD
gdm_inhibit_ac=1 # Inhibit suspend if on AC power but not logged (for servers with SSH access)
user_inhibit_ac=1 # Inhibit suspend when logged in and plugged into AC power
ignore_lid_switch=1 # Ignore suspend on closing lid tweak
install_neovim_gtk=1 # No binary packages yet, will build from source!
install_google_chrome=1 # The native .deb version is better than the Flatpak
install_windscribe=1 # VPN with slick Linux GUI! Use my referral link (https://windscribe.com/yo/jltrv4cs) to get an extra GB when you sign up for a FREE account, total of 11GB free VPN data per month!  AND you can do their tweet4data program to get an extra 5GB per month too!!
priv_firefox_launcher=1 # Add private window to context menu for Firefox-ESR launcher
load_mimetypes=1 # Load default applications mime types (double-click in Nautilus opens with your preferred app)
patched_font='Hack Nerd Font' # Because only 1337 hax0rz use a font called Hack
patched_font_size=9
move_system_monitor=1 # Move Gnome extension system-monitor to the right of all indicators (against screen edge)
move_workspace_indicator=1 # Move Gnome extension workspace-indicator to the left panel box (just to the left of the app menu)
remote_touchpad_port=16180 # Golden ratio port!  But you can use any port >= 1024 and <= 65535


apt_purges=(
	evolution
	power-profiles-daemon # Gnome power profiles saves battery by just limiting your CPU all the time, TLP is smarter
)


apt_installs=(
	# OS packages
	# linux-headers-amd64 # required for NVIDIA drivers
	# nvidia-driver
	# nvidia-legacy-390xx-driver
	# nvidia-driver-libs:i386 # For playing Windows games with wine and NVIDIA cards
	libnotify-bin # Dependency for move-system-monitor and move-workspace-indicator scripts
	tlp # Smarter power management and better battery life than power-profiles-daemon
	tlp-rdw
	flatpak
	gnome-software-plugin-flatpak
	rsync
	gufw
	vlc # VLC can fix subtitle/audio timing, step frame-by-frame, and play more video formats. It's the goodest!!
	catfish # Since we still cannot sort the search results in Nautilus...
	gir1.2-gtop-2.0 # Required for the system-monitor Gnome extension
	# libdvd-pkg # Uncomment to watch DVD movies with an internal/external DVD drive
	nautilus-dropbox # Be careful how many computers you have connected to the same account
	
	# Developer packages
	neovim
	libgtk-4-dev # Dependency for compiling neovim-gtk, comment out if not using neovim-gtk
	python3-venv
	tree
	ipython3
	
	# Apps
	gimp
	gimp-data-extras
	inkscape
	inkscape-open-symbols
	gnucash
	python3-gnucash
	# audacity
	# kdenlive # Beware the KDE dependencies!
	# krita # Beware the KDE dependencies!
	wine # Will add i386 architecture to apt for playing Win32 games
	steam
)


flatpaks=(
	com.github.xournalpp.xournalpp
	com.github.johnfactotum.Foliate
	org.libretro.RetroArch
	com.stepmania.StepMania # DDR uses vim arrows! Just another reason why vim > emacs
	com.github.iwalton3.jellyfin-media-player
	com.github.unrud.RemoteTouchpad
)


gnome_extensions=(
	# URLs for Gnome extensions to download, install, and enable
	https://extensions.gnome.org/extension/517/caffeine/
	https://extensions.gnome.org/extension/779/clipboard-indicator/
	https://extensions.gnome.org/extension/4651/notification-banner-reloaded/
	https://extensions.gnome.org/extension/72/recent-items/
	https://extensions.gnome.org/extension/355/status-area-horizontal-spacing/
	https://extensions.gnome.org/extension/3010/system-monitor-next/
	# https://extensions.gnome.org/extension/120/system-monitor/ # Not updated for bookworm yet...
	https://extensions.gnome.org/extension/2890/tray-icons-reloaded/
	https://extensions.gnome.org/extension/21/workspace-indicator/ # Pre-installed, but needs code adjustment for my preferred positioning on the top bar, so I'm downloading it instead
	# https://extensions.gnome.org/extension/1319/gsconnect/
	#     GSConnect is kinda cool, but some of the functionality does not work fully.
	#     The gufw (firewall) instructions will show extra steps if gsconnect is uncommented.

	# UUIDs for pre-installed Gnome extensions to enable only
	apps-menu@gnome-shell-extensions.gcampax.github.com
	drive-menu@gnome-shell-extensions.gcampax.github.com
	places-menu@gnome-shell-extensions.gcampax.github.com
)

