#!/usr/bin/bash


# This file holds all the variables that will be loaded and used to setup
# your Debian installation.  Please customize this for EACH computer and save
# it in something like the ~/Setup directory (can be configured to use a
# different directory in the *-setup.sh script itself.  Doing so will prevent
# merge errors in case you do a git pull later for a newer version.


# To disable a setting below, simply comment out the entire line
status_dir='status' # Holds script status between reboots, can be absolute path or relative (to script dir)
rm_dotfiles=1 # Remove all old .dotfiles (from prior Linux distributions)
GRUB_CMDLINE_LINUX_DEFAULT='quiet splash pci=noaer' # To be copied into /etc/default/grub, parms like "pci=noaer" go here
extra_repos=1 # Add contrib and non-free to sources.list
# ssd=1 # Uncomment if installed to an SSD
gdm_inhibit_ac=1 # Inhibit suspend if on AC power but not logged (for servers and SSH access)
ignore_lid_switch=1 # Ignore suspend on closing lid tweak
install_google_chrome=1 # The native .deb version is better than the Flatpak
install_windscribe=1 # VPN with slick Linux GUI!
priv_firefox_launcher=1 # Add private window to context menu for Firefox-ESR launcher
load_mimetypes=1 # Load Nautilus mime types for Neovim
patched_font='Hack Nerd Font 9' # Because only 1337 hax0rz use a font called Hack

# If using 1920x1080 screen resolution, highly recommend changing the default
# terminal window size in *-dconf.txt to 100 cols by 50 rows

# For minimize and maximize buttons on window title bars, add this line to *-gsettings.txt
# org.gnome.desktop.wm.preferences button-layout 'appmenu:minimize,maximize,close'


apt_purges=(
	evolution
	power-profiles-daemon # Gnome power profiles saves battery by just limiting your CPU all the time, TLP is smarter
)


apt_installs=(
	# OS packages
	# linux-headers-amd64 # required for NVIDIA drivers
	# nvidia-driver
	# nvidia-legacy-390xx-driver
	# firmware-misc-nonfree # Installed by default in bookworm
	# intel-microcode # Detected and installed by default in bookworm
	# amd64-microcode
	# firmware-realtek
	# firmware-atheros
	# firmware-iwlwifi
	# apt-listbugs
	tlp # Smarter power management and better battery life than power-profiles-daemon
	tlp-rdw
	# plymouth # Graphical boot, installed by default in bookworm
	flatpak
	gnome-software-plugin-flatpak
	rsync
	gufw
	vlc # Totem often doesn't work; VLC can fix subtitle/audio timing or step frame-by-frame
	catfish # Since we still cannot sort the search results in Nautilus...
	gir1.2-gtop-2.0 # Required for the system-monitor Gnome extension
	# libdvd-pkg # Uncomment to watch DVD movies with internal/external DVD drive
	nautilus-dropbox
	
	# Developer packages
	neovim
	python3-venv
	tree
	ipython3
	
	# Apps
	gimp
	gimp-data-extras
	inkscape
	inkscape-open-symbols
	gnucash
	python3-gnucash
	wine
	# nvidia-driver-libs:i386 # For playing Windows games with wine
	steam
)


flatpaks=(
	com.github.xournalpp.xournalpp
	com.github.johnfactotum.Foliate
	# org.kde.kdenlive
	org.libretro.RetroArch
	com.stepmania.StepMania # DDR uses vim arrows! Just another reason why vim > emacs
	com.github.iwalton3.jellyfin-media-player
)


extension_urls=(
	# https://extensions.gnome.org/extension/906/sound-output-device-chooser/ # Not needed anymore in Gnome 43
	https://extensions.gnome.org/extension/615/appindicator-support/
	https://extensions.gnome.org/extension/779/clipboard-indicator/
	https://extensions.gnome.org/extension/4651/notification-banner-reloaded/
	https://extensions.gnome.org/extension/72/recent-items/
	https://extensions.gnome.org/extension/3010/system-monitor-next/
	# https://extensions.gnome.org/extension/120/system-monitor/ # Not updated for bookworm yet...
)

