#!/usr/bin/bash


# Moves the Gnome extensions system-monitor or system-monitor-next to the right
# of all indicators (against screen edge).  Updates to extensions often moves
# them back to their default positions, which looks ugly!  User should not
# install both system-monitor and system-monitor-next simultaneously.


ext_uuid=($(ls $HOME/.local/share/gnome-shell/extensions/ | grep system-monitor -))

# $ext_uuid defaults to the first extension found with 'system-monitor' in its name
if [ -n "$ext_uuid" ]; then
	ext_dir="$HOME/.local/share/gnome-shell/extensions/$ext_uuid"
	new_addToPanelBox="Main.panel._addToPanelBox('system-monitor', tray, -1, panel);"
	if [ -z "$(grep "$new_addToPanelBox" $ext_dir/extension.js)" ]; then
		sed -i "s/Main.panel._addToPanelBox('system-monitor', tray, [-0-9]*, panel);/$new_addToPanelBox/" $ext_dir/extension.js
		sleep 1
		notify-send "system-monitor extension updated" "Please logout and login to reload it."
	fi
fi

