#!/usr/bin/bash


# This file holds all the variables that will be loaded and used to setup
# your Debian installation.  Please customize this for EACH computer and save
# it in something like the ~/Setup directory (can be configured to use a
# different directory in the *-setup.sh script itself.  Doing so will prevent
# merge errors in case you do a git pull later for a newer version.


status_dir='status' # Holds script status between reboots, can be absolute path or relative (to script dir)
GRUB_CMDLINE_LINUX_DEFAULT='quiet splash' # To be copied into /etc/default/grub, parms like "pci=noaer" go here
extra_repos=1 # Add contrib and non-free to sources.list
# ssd=1 # Uncomment if installed to an SSD
gdm_inhibit_ac=1 # Inhibit suspend if on AC power but not logged (for servers and SSH access)
ignore_lid_switch=1 # Ignore suspend on closing lid tweak
install_windscribe=1 # VPN with slick Linux GUI!
priv_firefox_launcher=1 # Add private window to context menu for Firefox-ESR launcher
load_mimetypes=1 # Load Nautilus mime types for Neovim
patched_font='Hack Nerd Font 9'


apt_purges=(
	evolution
)


apt_installs=(
	# linux-headers-amd64 # required for NVIDIA drivers
	firmware-misc-nonfree
	intel-microcode
	# amd64-microcode
	# firmware-realtek
	# firmware-atheros
	# firmware-iwlwifi
	tlp # Newer version in backports for newer kernels
	tlp-rdw # Newer version in backports for newer kernels
	plymouth # Graphical boot
	flatpak
	gnome-software-plugin-flatpak
	rsync
	gufw
	vlc
	libavcodec-extra
	ipython3
	catfish # Since file searching in Nautilus sucks...
	gir1.2-gtop-2.0 # Required for the system-monitor Gnome extension
	libdvd-pkg # Uncomment to watch DVD movies with internal/external DVD drive
	# nautilus-dropbox
	neovim # For bullseye, comment out to install latest release from GitHub!
	python3-neovim
	xclip # For clipboard sharing with Neovim
	gimp
	gimp-data-extras
	inkscape
	inkscape-open-symbols
	gnucash
	python3-gnucash
	wine
	# nvidia-driver
	# nvidia-legacy-390xx-driver
)


flatpaks=(
	com.google.Chrome
	com.github.xournalpp.xournalpp
	com.github.johnfactotum.Foliate
	org.kde.kdenlive
	org.libretro.RetroArch
	com.stepmania.StepMania
	com.github.iwalton3.jellyfin-media-player
)


extension_urls=(
	https://extensions.gnome.org/extension/906/sound-output-device-chooser/
	https://extensions.gnome.org/extension/72/recent-items/
	https://extensions.gnome.org/extension/779/clipboard-indicator/
	https://extensions.gnome.org/extension/3010/system-monitor-next/ # For sid
)

